/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AccordionEvent } from "./components/accordion/v-accordion-section/types";
export { AccordionEvent } from "./components/accordion/v-accordion-section/types";
export namespace Components {
    interface CookiePolicy {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface VAccordion {
    }
    interface VAccordionSection {
        "headingLevel"?: number;
        "sectionTitle": string;
    }
    interface VButton {
        /**
          * The appearance of the button.
         */
        "appearance"?: typeof this.ButtonAppearance[keyof typeof this.ButtonAppearance];
        /**
          * Whether the button should have dense padding.
         */
        "dense"?: boolean;
        /**
          * Whether the button should be disabled.
         */
        "disabled"?: boolean;
        /**
          * Optional class(es) to pass to the button element.
         */
        "extraClassNames"?: string;
        /**
          * If this is set, the button will be rendered as a <a> tag with the link provided.
         */
        "href"?: string;
        /**
          * Whether the button should display inline.
         */
        "inline"?: boolean;
        /**
          * Whether the should display a loading spinner.
         */
        "isProcessing"?: boolean;
        /**
          * Wether the button should be small.
         */
        "small"?: boolean;
    }
}
export interface VAccordionSectionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVAccordionSectionElement;
}
declare global {
    interface HTMLCookiePolicyElement extends Components.CookiePolicy, HTMLStencilElement {
    }
    var HTMLCookiePolicyElement: {
        prototype: HTMLCookiePolicyElement;
        new (): HTMLCookiePolicyElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVAccordionElement extends Components.VAccordion, HTMLStencilElement {
    }
    var HTMLVAccordionElement: {
        prototype: HTMLVAccordionElement;
        new (): HTMLVAccordionElement;
    };
    interface HTMLVAccordionSectionElement extends Components.VAccordionSection, HTMLStencilElement {
    }
    var HTMLVAccordionSectionElement: {
        prototype: HTMLVAccordionSectionElement;
        new (): HTMLVAccordionSectionElement;
    };
    interface HTMLVButtonElement extends Components.VButton, HTMLStencilElement {
    }
    var HTMLVButtonElement: {
        prototype: HTMLVButtonElement;
        new (): HTMLVButtonElement;
    };
    interface HTMLElementTagNameMap {
        "cookie-policy": HTMLCookiePolicyElement;
        "my-component": HTMLMyComponentElement;
        "v-accordion": HTMLVAccordionElement;
        "v-accordion-section": HTMLVAccordionSectionElement;
        "v-button": HTMLVButtonElement;
    }
}
declare namespace LocalJSX {
    interface CookiePolicy {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VAccordion {
    }
    interface VAccordionSection {
        "headingLevel"?: number;
        "onToggle"?: (event: VAccordionSectionCustomEvent<AccordionEvent>) => void;
        "sectionTitle"?: string;
    }
    interface VButton {
        /**
          * The appearance of the button.
         */
        "appearance"?: typeof this.ButtonAppearance[keyof typeof this.ButtonAppearance];
        /**
          * Whether the button should have dense padding.
         */
        "dense"?: boolean;
        /**
          * Whether the button should be disabled.
         */
        "disabled"?: boolean;
        /**
          * Optional class(es) to pass to the button element.
         */
        "extraClassNames"?: string;
        /**
          * If this is set, the button will be rendered as a <a> tag with the link provided.
         */
        "href"?: string;
        /**
          * Whether the button should display inline.
         */
        "inline"?: boolean;
        /**
          * Whether the should display a loading spinner.
         */
        "isProcessing"?: boolean;
        /**
          * Wether the button should be small.
         */
        "small"?: boolean;
    }
    interface IntrinsicElements {
        "cookie-policy": CookiePolicy;
        "my-component": MyComponent;
        "v-accordion": VAccordion;
        "v-accordion-section": VAccordionSection;
        "v-button": VButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cookie-policy": LocalJSX.CookiePolicy & JSXBase.HTMLAttributes<HTMLCookiePolicyElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "v-accordion": LocalJSX.VAccordion & JSXBase.HTMLAttributes<HTMLVAccordionElement>;
            "v-accordion-section": LocalJSX.VAccordionSection & JSXBase.HTMLAttributes<HTMLVAccordionSectionElement>;
            "v-button": LocalJSX.VButton & JSXBase.HTMLAttributes<HTMLVButtonElement>;
        }
    }
}
